name: Deploy application

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy_app:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Install pnpm
              uses: pnpm/action-setup@v2
            - name: Install Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Lint
              run: pnpm lint
            - name: Run tests
              run: pnpm test:ci
              env:
                  VITE_TOKEN: ${{ secrets.VITE_TOKEN }}
                  VITE_URL: ${{ secrets.VITE_URL }}
            - name: Deploy production to Netlify
              uses: nwtgck/actions-netlify@v2.0
              with:
                  production-branch: main
                  production-deploy: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  deploy-message: ${{ github.event.head_commit.message }}
                  publish-dir: './dist'
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1
