# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test application

on:
    # this job should run only on PRs and not main
    #  and on main you should have another job which runs only on main and tests and deploy (probably another workflow file)
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    test:
        # This job called "test" runs on every PR and on main branch
        # we need to deploy our application to Netlify on PR merge into main or when pushing to main
        # but before we deploy to Netlify, we need to run linting and testing and if those pass then we deploy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Lint
              run: pnpm lint
            - name: Run tests
              run: pnpm test:ci
              env:
                  VITE_TOKEN: ${{ secrets.VITE_TOKEN }}
                  VITE_URL: ${{ secrets.VITE_URL }}
